In [1]:
import pandas as pd

In [2]:
def load_data():
    try :
        df = pd.read_csv("sys_data.csv")
        return df
    except FileNotFoundError :
        print("Make sure you have file in this directory")
        return None
    except Exception as e :
        print(f"Error : {str(e)}")
        return None
df = load_data()

In [3]:
df.head()

             timestamp  cpu_usage  memory_usage  disk_usage
0  2026-01-15 15:50:01        4.9          28.3        39.5
1  2026-01-15 15:51:01        3.0          28.5        39.5
2  2026-01-15 15:52:01        5.8          28.4        39.5
3  2026-01-15 15:53:01       30.7          30.3        39.5
4  2026-01-15 15:54:01        5.8          27.7        39.5

In [4]:
df.tail()

               timestamp  cpu_usage  memory_usage  disk_usage
323  2026-01-16 16:34:01        8.5          59.9        42.7
324  2026-01-16 16:35:01        4.5          59.7        42.7
325  2026-01-16 16:36:01       12.9          60.0        42.7
326  2026-01-16 16:37:01       11.5          54.9        42.7
327  2026-01-16 16:38:01       31.8          49.1        42.7

In [5]:
df.isnull().sum()

timestamp       0
cpu_usage       0
memory_usage    0
disk_usage      0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328 entries, 0 to 327
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     328 non-null    object
 1   cpu_usage     328 non-null    float64
 2   memory_usage  328 non-null    float64
 3   disk_usage    328 non-null    float64
dtypes: float64(3), object(1)
memory usage: 10.4+ KB

In [8]:
df.shape

(328, 4)

In [9]:
df.columns

Index(['timestamp', 'cpu_usage', 'memory_usage', 'disk_usage'], dtype='object')

In [10]:
df.describe()

        cpu_usage  memory_usage  disk_usage
count  328.000000    328.000000  328.000000
mean    11.006098     41.630793   41.153659
std     11.542964     13.850239    1.522628
min      0.300000     15.300000   39.500000
25%      3.000000     28.100000   39.500000
50%      7.100000     45.950000   42.100000
75%     14.525000     53.000000   42.600000
max     98.300000     68.600000   44.100000

In [11]:
df["timestamp"].dtype

dtype('O')

In [12]:
df["timestamp"] = pd.to_datetime(df["timestamp"], errors = "coerce")

In [13]:
df["timestamp"].dtype

dtype('<M8[ns]')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328 entries, 0 to 327
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     328 non-null    datetime64[ns]
 1   cpu_usage     328 non-null    float64
 2   memory_usage  328 non-null    float64
 3   disk_usage    328 non-null    float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 10.4 KB

In [15]:
df.columns

Index(['timestamp', 'cpu_usage', 'memory_usage', 'disk_usage'], dtype='object')

In [16]:
def create_time_feature(df):
    df["year"] = df["timestamp"].dt.year
    df["month"] = df["timestamp"].dt.month
    df["day"] = df["timestamp"].dt.day
    df["hour"] = df["timestamp"].dt.hour
    df["minute"] = df["timestamp"].dt.minute
    df["day_of_week"] = df["timestamp"].dt.day_name()
    df["month_name"] = df["timestamp"].dt.month_name()
    df["day_of_year"] = df["timestamp"].dt.dayofyear
    return df

df = create_time_feature(df)

In [17]:
df.columns

Index(['timestamp', 'cpu_usage', 'memory_usage', 'disk_usage', 'year', 'month',
       'day', 'hour', 'minute', 'day_of_week', 'month_name', 'day_of_year'],
      dtype='object')

In [18]:
df.head()

,timestamp,cpu_usage,memory_usage,disk_usage,year,month,day,hour,minute,day_of_week,month_name,day_of_year
0,2026-01-15 15:50:01,4.9,28.3,39.5,2026,1,15,15,50,Thursday,January,15
1,2026-01-15 15:51:01,3.0,28.5,39.5,2026,1,15,15,51,Thursday,January,15
2,2026-01-15 15:52:01,5.8,28.4,39.5,2026,1,15,15,52,Thursday,January,15
3,2026-01-15 15:53:01,30.7,30.3,39.5,2026,1,15,15,53,Thursday,January,15
4,2026-01-15 15:54:01,5.8,27.7,39.5,2026,1,15,15,54,Thursday,January,15